config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root :to => 'chores#index'
  resources :chores do
    collection do
      get :get_chores
      post :move
      post :resize
    end
  end

  get 'auth/twitter/callback', to: 'sessions#twitter', as: :twitter_auth
  get 'auth/failure', to: 'sessions#failure'
 

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  belongs_to :user

  scope :created_in_last_week, -> { where("created_at >= ?", 1.week.ago.utc).order(endtime: :desc).limit(5) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:twitter]

  has_many :chores

  after_create :send_welcome_email

  scope :created_in_last_week, -> { where("created_at >= ?", 1.week.ago.utc).order(endtime: :desc).limit(5) }

  def self.from_twitter(auth)
    create! do |user|
     user.name = auth.info.nickname
     user.uid = auth.uid
     user.password = SecureRandom.hex
    end
 end

private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def twitter
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:show, :edit, :update, :destroy]

  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
  end

  # GET /chores/new
  def new
    @chore = Chore.new
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(chore_params)

    respond_to do |format|
      if @chore.save
        format.html { redirect_to @chore, notice: 'Chore was successfully created.' }
        format.json { render :show, status: :created, location: @chore }
      else
        format.html { render :new }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to @chore, notice: 'Chore was successfully updated.' }
        format.json { render :show, status: :ok, location: @chore }
      else
        format.html { render :edit }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore.destroy
    respond_to do |format|
      format.html { redirect_to chores_url, notice: 'Chore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = Chore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chore_params
      params.require(:chore).permit(:title, :url, :starttime, :endtime, :allday, :default, :chore_location)
    end
end

app/controllers/sessions_controller.rb
def twitter
  auth = request.env["omniauth.auth"]
  user = User.where(uid: auth["uid"]).first || User.from_twitter(auth)
  if user
    session[:user_id] = user.id
    flash[:notice] = "You have been logged in through Twitter."
    redirect_back_or root_url
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/_form.html.erb
<%= bootstrap_form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.datetime_select :starttime %>
  </div>
  <div class="field">
    <%= f.datetime_select :endtime %>
  </div>
  <div class="field">
    <%= f.check_box :allday %>
  </div>
  <div class="field">
    <%= f.text_field :chore_location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing Chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<%= menu_item "New Chore", new_chore_path, class: 'btn-lg btn-info btn-block text-center' %>
<br>
<script>
  $(document).ready(function() {
    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();
   
   $('#calendar').fullCalendar({
   editable: true,
   header: {
     left: 'prev,next today',
     center: 'title',
     right: 'month,agendaWeek,agendaDay'
   },
   defaultView: 'agendaWeek',
   slotMinutes: 15,
   loading: function(bool){
     if (bool)
       $('#loading').show();
     else
       $('#loading').hide();
   },
   timeFormat: 'h:mm t ',
   dragOpacity: "0.5",
  
   events: {
    url: '/chores',
    type: 'GET',
    error: function() {
      alert('there was an error while fetching events!');
    },
    
   backgroundColor: 'blue',
   textColor: 'white'
   }
   });
   });
</script>

<div id='loading' style='display:none'>loading...</div>
<div id='calendar'></div>

app/views/chores/new.html.erb
<h1>New Chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @chore.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @chore.url %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @chore.starttime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @chore.endtime %>
</p>

<p>
  <strong>Allday:</strong>
  <%= @chore.allday %>
</p>

<p>

<p>
  <strong>Chore location:</strong>
  <%= @chore.chore_location %>
</p>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>

app/views/layouts/_user_header.html.erb
  <% if user_signed_in? %>
<ul class="nav nav-pills pull-left">
  <%= link_to "Home", root_path, :class => 'navbar-link' %>
</ul>
<ul class="nav nav-pills pull-right">
    Logged in as <strong><%= current_user.email %></strong>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
</ul>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-narrow">
  <div class="masthead">
    <%= render 'layouts/user_header' %>
    <h5 class="text-center">A Chore Tracking Application</h5>
  </div>
  <hr />
</div>

<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<% if !user_signed_in? %>
  <%= link_to "Sign up", new_user_registration_path, class: 'btn-lg btn-info btn-block text-center'  %>
  <%= link_to "Login", new_user_session_path, class: 'btn-lg btn-info btn-block text-center'  %>
  <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter), class: 'btn-lg btn-info btn-block text-center' %>
  <% end %>

<%= yield %>

</body>
</html>